### ISSUE TITLE
Scrolling with Magic

### ISSUE THREAD

**Issue by caneco** [d4nyll/smartscroll#1] opened 2015-05-03 09:37 UTC
Hello,
Have you tried to scroll your demo with an Apple Magic Mouse? It's always passing 2 slides each time.

**Comment by d4nyll** [comment] 2015-05-03 10:51
Hi Caneco, thanks for getting in touch!

smartscroll does not currently support touch events, such as on mobiles; it also has not been optimized for trackpads or the Apple Magic Mouse, so what you reported is expected.

I think the issue is similar to [this issue](https://github.com/jquery/jquery-mousewheel/issues/36) on [jquery/jquery-mousewheel](https://github.com/jquery/jquery-mousewheel), where momentum (or inertia) scrolling means scroll events are being fired long after the fingers left the trackpad or mouse. Have a look at this [demo](http://jsfiddle.net/n7bk6pb9/1/).

I will investigate the best solutions and try to implement it. I will close this issue and open a more general issue regarding momentum / inertia scrolling. If you have any ideas of how to tackle this, please do comment there.

As always, pull requests are welcomed!

**Closed as completed by d4nyll** 2015-05-03 10:51 UTC
